pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven {
            name = 'PaperMC'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        maven {
            name = 'PlaceholderAPI'
            url = 'https://repo.extendedclip.com/releases/'
        }
        maven {
            name = 'JitPack'
            url = 'https://jitpack.io'
        }
    }
}

rootProject.name = 'LuckPrefix'
